# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 742fe0b8cfe371c5aa006858f49276701024aa172e0ac69939d33ed5e38024ff8c9286902bcd48f12b19d17396784fe81c2862a670dc4a6a1c80d4ed9d8a1a74

test:
  secret_key_base: a316aab12f0bd6ac9cbdaade2bc067c43e7e5edc4b6188e6576e29e8af4704ab1014f34655b817d8db0a0ff69c1321101e3c3ec4a3cc7b6d28e07a1fb2ee69da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
